# We need ruby 3.0.0. I found this from docker hub
FROM ruby:3.0.0

# Exposing port 5000
EXPOSE 5000

# Setting working directory
WORKDIR /usr/src/app

# Installing node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt install -y nodejs

# Copy all of the content from the project to the image
COPY . .

# Installing node packages
RUN npm install

# Adding enviroment variable
ENV BACKEND_URL=http://localhost:8080

# Generating static files into build folder and passing BACKEND_URL as argument
RUN REACT_APP_BACKEND_URL=$BACKEND_URL npm run build

# Installing serve package
RUN npm install -g serve

# Command
CMD ["serve", "-s", "-l", "5000", "build"]